# .github/workflows/deploy.yaml
name: Deploy Package to Pypi
on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Twine
        run: | 
          pip install twine
      - name: Build package
        run: |
          python setup.py sdist
      - name: Upload Package
        run: |
          twine upload dist/* -u ${{ secrets.TWINE_USERNAME }} -p ${{secrets.TWINE_PASSWORD}}
